'use client'

import { useLanguage } from '@/hooks/useLanguage'
import { EMAIL, GITHUB_URL, LINKEDIN_URL, NAME, PHONE } from '@/utils/constants'
import { Dot, Github, Linkedin, Mail, Phone } from 'lucide-react'
import Image from 'next/image'
import { ReactNode } from 'react'

function Title({ children }: { children: ReactNode }) {
	return <h3 className="font-semibold text-xl mb-2">{children}</h3>
}

export default function Resume() {
	const { texts } = useLanguage()

	return (
		<main className="grid grid-cols-[2fr,3fr] gap-10 p-4 bg-white text-black h-[1100px] w-[810px]">
			<div className="flex items-center justify-center max-h-max">
				<Image
					src="/avatar.jpg"
					alt="Gabriel avatar generated by an AI"
					width={200}
					height={200}
					className="rounded-3xl hover:scale-125 duration-300"
				/>
			</div>
			<div className="flex flex-col gap-4 justify-center">
				<h1 className="text-3xl">{texts.main.job}</h1>
				<h2 className="text-2xl font-semibold">{NAME}</h2>
				<a className="underline underline-offset-4" href={window.location.origin} target="_blank">
					{window.location.origin}
				</a>
			</div>

			<div className="flex flex-col gap-6">
				<div>
					<Title>👨‍💻 {texts.about.title}</Title>
					<p>{texts.about.description}</p>
				</div>

				<div>
					<Title>📚 {texts.academic.title}</Title>
					<ul className="flex flex-col gap-2">
						{texts.academic.list.map((item, index) => (
							<li key={index} className="flex flex-col">
								<span className="font-semibold flex items-center">
									<Dot />
									{item.title}
								</span>
								<span>{item.institution}</span>
							</li>
						))}
					</ul>
				</div>

				<div>
					<Title>🛠️ {texts.skills.title}</Title>
					<ul className="flex items-center gap-2 flex-wrap">
						{texts.skills.list.map((item, index) => (
							<li key={index} className="flex items-center">
								<Dot />
								<span>{item}</span>
							</li>
						))}
					</ul>
				</div>

				<div>
					<Title>👤 {texts.contact.title}</Title>
					<ul>
						<li className="flex items-center gap-1">
							<Mail size={16} />
							<a className="underline underline-offset-4" href={`mailto:${EMAIL}`}>
								{EMAIL}
							</a>
						</li>
						<li className="flex items-center gap-1">
							<Phone size={16} /> <span>{PHONE}</span>
						</li>
						<li className="flex items-center gap-1">
							<Github size={16} />{' '}
							<a className="underline underline-offset-4" href={GITHUB_URL} target="_blank">
								{GITHUB_URL}
							</a>
						</li>
						<li className="flex items-center gap-1">
							<Linkedin size={16} />{' '}
							<a className="underline underline-offset-4" href={LINKEDIN_URL} target="_blank">
								{LINKEDIN_URL}
							</a>
						</li>
					</ul>
				</div>
			</div>

			<div className="flex flex-col gap-6">
				<div>
					<Title>🌟 {texts.professional.title}</Title>
					<ul className="flex flex-col gap-2">
						{texts.professional.list.map((item, index) => (
							<li key={index} className="flex flex-col">
								<div className="flex items-center">
									<Dot />
									<span className="font-semibold">{item.role}</span>
								</div>
								<span>{item.company}</span>
								<p>{item.description}</p>
							</li>
						))}
					</ul>
				</div>

				<div>
					<Title>🚀 {texts.projects.title}</Title>
					<ul className="flex flex-col gap-2">
						{texts.projects.list.map((item, index) => (
							<li key={index} className="flex flex-col">
								<div className="flex items-center">
									<Dot />
									<span className="font-semibold">{item.title}</span>
								</div>
								<p>{item.description}</p>
								<div className="flex items-center gap-2 text-sm">
									{item.source && (
										<a href={item.source} target="_blank" className="underline underline-offset-4">
											{texts.projects.source}
										</a>
									)}
									{item.website && (
										<a href={item.website} target="_blank" className="underline underline-offset-4">
											{texts.projects.website}
										</a>
									)}
								</div>
							</li>
						))}
					</ul>
				</div>
			</div>
		</main>
	)
}
